apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: discord-api
  template:
    metadata:
      labels:
        deployment: discord-api
    spec:
      containers:
      - name: the-container
        image: sa46lll/docker-image:latest
        ports:
        - containerPort: 8080
